# Generated by Django 5.1 on 2025-02-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Income'),
        ),
    ]
